from webapp.views import *
from django.urls import path

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('carrito/', CarritoView.as_view(), name='carrito'),
    path('servicios/', ServiciosView.as_view(), name='servicios'),

    path("servicios/cargar/", CargarEspaciosView.as_view(), name="cargar_espacios"),
    path('servicios/detalle/<int:id>/', ServiciosDetalleView.as_view(), name='servicios_detalle'),
    path("servicios/verificar-disponibilidad/", verificar_disponibilidad, name="verificar_disponibilidad"),
    path('servicios/detalle-json/<int:id>/', ServiciosDetalleJsonView.as_view(), name='servicio_detalle_json'),

    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("api/register/", api_register, name="api_register"),
    path("api/login/", LoginAPIView.as_view(), name="api_login"),
    path("reservas/", ReservasView.as_view(), name="reservas"),
    path("api/reservas/<int:usuario_id>/", api_reservas_por_usuario, name="api_reservas_usuario"),
    path("pago/", PagosView.as_view(), name="pago"),
    path("api/pagos/<int:usuario_id>/", api_pagos_por_usuario, name="api_pagos_usuario"),
    path("usuario/<int:usuario_id>/", UsuarioDetalleView.as_view(), name="usuario_perfil"),
    path("api/usuario/<int:usuario_id>/", api_usuario_por_id, name="api_usuario_por_id"),
    path("api/reservas/<int:reserva_id>/detalles/", api_detalles_reserva, name="api_detalles_reserva"),
    path("api/reservas/<int:reserva_id>/pagos/", api_pagos_reserva, name="api_pagos_reserva"),
    path("api/reservas/precrear/", api_pre_reserva, name="api_pre_reserva"),
    path("api/reservas/confirmar/", api_confirmar_reserva, name="api_confirmar_reserva"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("dashboard/politicas/", PoliticasDashboardView.as_view(), name="dashboard_politicas"),
    path("api/politicas/", api_seleccionar_politicas, name="api_politicas_listar"),
    path("api/politicas/<int:id>/", api_actualizar_politica, name="api_politicas_actualizar"),
    path("api/politicas/<int:id>/", api_eliminar_politica, name="api_politicas_eliminar"),
    path("api/politicas/", api_insertar_politica, name="api_politicas_insertar"),
    path("dashboard/usuarios/", UsuariosDashboardView.as_view(), name="dashboard_usuarios"),
    path("api/usuarios/", api_usuarios_listar, name="api_usuarios_listar"),
    path("api/usuarios/", api_usuarios_insertar, name="api_usuarios_insertar"),
    path("api/usuarios/<int:id>/", api_usuarios_actualizar, name="api_usuarios_actualizar"),
    path("api/usuarios/<int:id>/", api_usuarios_eliminar, name="api_usuarios_eliminar"),
    path("dashboard/reservas/", ReservasDashboardView.as_view(), name="dashboard_reservas"),
    path("api/reservas/", api_reservas_listar, name="api_reservas_listar"),
    path("api/reservas/", api_reservas_insertar, name="api_reservas_insertar"),
    path("api/reservas/<int:id>/", api_reservas_actualizar, name="api_reservas_actualizar"),
    path("api/reservas/<int:id>/", api_reservas_eliminar, name="api_reservas_eliminar"),
    path("dashboard/espacios/", EspaciosDashboardView.as_view(), name="dashboard_espacios"),
    path("api/espacios/", api_espacios_listar, name="api_espacios_listar"),
    path("api/espacios/", api_espacios_insertar, name="api_espacios_insertar"),
    path("api/espacios/<int:id>/", api_espacios_actualizar, name="api_espacios_actualizar"),
    path("api/espacios/<int:id>/", api_espacios_eliminar, name="api_espacios_eliminar"),

    path("dashboard/pagos/", PagosDashboardView.as_view(), name="dashboard_pagos"),

    path("api/pagos/", api_pagos_listar, name="api_pagos_listar"),
    path("api/pagos/", api_pagos_insertar, name="api_pagos_insertar"),
    path("api/pagos/<int:id>/", api_pagos_actualizar, name="api_pagos_actualizar"),
    path("api/pagos/<int:id>/", api_pagos_eliminar, name="api_pagos_eliminar"),
]
